/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class AcercaDe extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public AcercaDe() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t = new javax.swing.JLabel();
        comprador = new javax.swing.JLabel();
        VolverB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        copy = new javax.swing.JLabel();
        flecha = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 58, 188));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setText("ElectronicShop");
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        comprador.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        comprador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comprador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_help_100px.png"))); // NOI18N
        jPanel1.add(comprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        VolverB.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        VolverB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        VolverB.setText("Volver");
        VolverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBActionPerformed(evt);
            }
        });
        jPanel1.add(VolverB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 100, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 340, 190));
        jLabel1.setText("<html>Somos una empresa que ha desarrollado una plataforma de ventas virtual de productos inteligentes como los computadores y sus partes principales desde el 2021. Por ende, brindamos información detallada acerca de nuestros productos, para así enviarlos a todos los lugares de Colombia.<html>");

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 410));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_menu_64px.png"))); // NOI18N
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        copy.setForeground(new java.awt.Color(255, 255, 255));
        copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copy.setText("2021 ElectronicShop todos los derechos reservados");
        jPanel1.add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 300, 20));

        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_double_down_64px.png"))); // NOI18N
        jPanel1.add(flecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        cp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_copyright_64px.png"))); // NOI18N
        jPanel1.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBActionPerformed

         Menu menu =  new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverBActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton VolverB;
    private javax.swing.JLabel comprador;
    private javax.swing.JLabel copy;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel flecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
