/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class Categorias extends javax.swing.JFrame {

    private final String nombreComponente;

    /**
     * Creates new form Menu
     */
    public Categorias(String nombreComponente) {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.nombreComponente = nombreComponente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        empresaB = new javax.swing.JButton();
        personalB = new javax.swing.JButton();
        gamingB = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        copy = new javax.swing.JLabel();
        flecha = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 58, 188));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué categoría de productos deseas ver?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 560, 100));

        t.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setText("ElectronicShop");
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        precio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_company_64px.png"))); // NOI18N
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_computer_64px.png"))); // NOI18N
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_game_controller_64px.png"))); // NOI18N
        jPanel1.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        empresaB.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        empresaB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        empresaB.setText("Empresarial");
        empresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaBActionPerformed(evt);
            }
        });
        jPanel1.add(empresaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 100, -1));

        personalB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        personalB.setText("Personal");
        personalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalBActionPerformed(evt);
            }
        });
        jPanel1.add(personalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 100, -1));

        gamingB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        gamingB.setText("Gaming");
        gamingB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamingBActionPerformed(evt);
            }
        });
        jPanel1.add(gamingB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 100, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 630, 410));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_menu_64px.png"))); // NOI18N
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        copy.setForeground(new java.awt.Color(255, 255, 255));
        copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copy.setText("2021 ElectronicShop todos los derechos reservados");
        jPanel1.add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 300, 20));

        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_double_down_64px.png"))); // NOI18N
        jPanel1.add(flecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        cp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_copyright_64px.png"))); // NOI18N
        jPanel1.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaBActionPerformed
        MostrarDatos menuDatos  = new MostrarDatos(nombreComponente, "Categoria", "Empresarial");
        menuDatos.setVisible(true);
        this.setVisible(false);
 

    }//GEN-LAST:event_empresaBActionPerformed

    private void personalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalBActionPerformed
        // TODO add your handling code here:
        MostrarDatos menuDatos  = new MostrarDatos(nombreComponente, "Categoria", "Personal");
        menuDatos.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_personalBActionPerformed

    private void gamingBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamingBActionPerformed
        // TODO add your handling code here
           MostrarDatos menuDatos  = new MostrarDatos(nombreComponente, "Categoria", "Gaming");
        menuDatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gamingBActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel copy;
    private javax.swing.JLabel cp;
    private javax.swing.JButton empresaB;
    private javax.swing.JLabel flecha;
    private javax.swing.JButton gamingB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel menu;
    private javax.swing.JButton personalB;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
